cc_test(
    name = "stl_test",
    srcs = ["stl_test.cpp"],
    deps = [
        "//:mylib",
        "@googletest//:gtest_main",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "smart_pointers_test",
    srcs = ["smart_pointers_test.cpp"],
    deps = [
        "//:mylib",
        "@googletest//:gtest_main",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "concurrency_test",
    srcs = ["concurrency_test.cpp"],
    deps = [
        "//:mylib",
        "@googletest//:gtest_main",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "patterns_test",
    srcs = ["patterns_test.cpp"],
    deps = [
        "//:mylib",
        "@googletest//:gtest_main",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "system_design_test",
    srcs = ["system_design_test.cpp"],
    deps = [
        "//:mylib",
        "@googletest//:gtest_main",
    ],
    copts = ["-std=c++20"],
)
